ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.taskboard.ApplicationKt.module ]
    }
}

app {
    name = "taskboard-api"
    environment = ${?APP_ENV}
    environment = development
}
